GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/2 HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Dan Abramov",
  "number": 12345
}

